version: '1'
services:
   app:
     image: 'adoptopenjdk:11-jre-hotspot'
     build:
       context: .
       dockerfile: app.dockerfile
     ports: 
       - 8080:8080
     container_name: app
     depends_on:
       - db
     networks:
       - ocarsionplus
   db:
     image: 'postgres:latest'
     build:
        context: .
        dockerfile: postgres.dockerfile
     ports: 
       - 5432:5432     
     container_name: db
     environment:
       - POSTGRES_USER=ocarsionplus
       - POSTGRES_PASSWORD=ocarsionplus
     networks:
       - ocarsionplus
 
networks:
    ocarsionplus:
        driver: bridge