package com.grupolemon.ocarsionplus.model;

public enum ServicioEnum {
EXPORT_CARS, LIST_CAR_FILTERED, DETALLE_COCHE, MARCA_UPDATE, MARCA_GET, MARCA_CREATE, MARCA_DELETE, USUARIO_CREATE, USUARIO_DELETE, USUARIO_UPDATE, USUARIO_GET, DETALLE_COCHE_EN_VIGOR, COCHE_UPDATE, COCHE_DELETE, COCHE_CREATE, PRECIO_CREATE, PRECIO_DELETE, PRECIO_UPDATE, PRECIO_GET, EXTRA_CREATE, EXTRA_DELETE, EXTRA_UPDATE, EXTRA_GET
}
